
DESIRED_FPS = 60

SHOW_FPS = False

PADDLE_ACCELERATION = 0.6
PADDLE_FRICTION = 0.2
PADDLE_TERMINAL_VELO = 6

# The ball's maximum velocity vector magnitude.
BALL_BASE_RESULTANT_VELOCITY = 4
BALL_MAX_RESULTANT_VELOCITY = 8

# How many tiles in a level?
TILE_PER_ROW = 12
TILE_ROW_COUNT = 6

# Parallax Background scale size
PARALLAX_BG_SCALE = 1.5

# Particles configurations
MIN_PARTICLE_ON_COLLISION = 4
MAX_PARTICLE_ON_COLLISION = 7
PARTICLE_MAX_SIZE = 12
PARTICLE_MIN_SIZE = 3
PARTICLE_SPEED = 1
PARTICLE_FADING_SPEED = 2

# Powerup Configurations
POWERUP_DROP_CHANCE = 0.08    # 0 to 1
POWERUP_DROP_SPEED = 2

POWERUP_WEIGHTS = ( 0.2, 0.2, 0.2, 0.2, 0.2 )   # Probability of each powerup appearing. MUST sum to 1.

RECOVER_HEALTH_POWER = 1

STRONG_BALL_DURATION = 30

LONG_PADDLE_DURATION = 30
LONG_PADDLE_SCALE = 1.5

DOUBLE_BALL_DURATION = 60

INTO_THE_FUTURE_PREDICTIONS = 10
INTO_THE_FUTURE_BASE_ALPHA = 64
INTO_THE_FUTURE_STEP = 12
INTO_THE_FUTURE_DURATION = 60
